import type { Metadata } from "next";
// import localFont from "next/font/local";
import localFont from "next/font/local"
import "./globals.css";
import Navbar from "./components/navbar/navbar";



const spaceGrotesk = localFont({
  src: './fonts/SpaceGrotesk-Light.woff',
  variable: '--font-grotesk',
  weight: '100 200 300 400 500 600 700 800 900 '
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} mx-24 max-sm:mx-4 max-md:mx-16  2xl:mx-60 3xl:mx-[35rem]`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
